---
minimum_pre_commit_version: 3.7.0

repos:

# commit-msg hooks
# ----------

# Conventional Commit message checker (commitizen)
- repo: https://github.com/commitizen-tools/commitizen
  rev: v4.4.1
  hooks:
  - id: commitizen
    stages:
    - commit-msg

# pre-commit hooks
# ----------

# Standard pre-commit rules
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
  - id: check-toml
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - id: trailing-whitespace
    args:
    - --markdown-linebreak-ext=md
# isort (in black-compatibility mode)
- repo: https://github.com/pycqa/isort
  rev: 6.0.1
  hooks:
  - id: isort
    args:
    - --profile
    - black
    - --filter-files
# Black (uncompromising) Python code formatter
- repo: https://github.com/psf/black
  rev: 25.1.0
  hooks:
  - id: black
    args:
    - --target-version
    - py312
# MyPy
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.15.0
  hooks:
  - id: mypy
    files: ^workflow
    args:
    - --install-types
    - --non-interactive
# YAML Lint
- repo: https://github.com/adrienverge/yamllint
  rev: v1.35.1
  hooks:
  - id: yamllint
# Pylint
- repo: https://github.com/pycqa/pylint
  rev: v3.3.1
  hooks:
  - id: pylint
    name: pylint
    entry: pylint
    additional_dependencies:
    - jinja2 >= 3.1.3
    - jsonschema >= 4.21.1
    - pyyaml >= 5.3.1, < 7.0
    - im-protobuf >= 8.2.0
    - im-data-manager-job-decoder >= 2.1.0
    files: ^workflow/.*\.py$
